master:
  merge_request:
    - stages:
        - name: make commitlist
          type: git:commitList
          options:
            toFile: commits-data.json
        - name: do commitlint
          image: csighub.tencentyun.com/plugins/commitlint:latest
          settings:
            from_file: commits-data.json
$:
  tag_push:
    - stages:
        - name: changelog
          type: git:changeLog
          options:
            filename: CHANGELOG.md
            target: master
          exports:
            latestChangeLog: LATEST_CHANGE_LOG
        - name: upload release
          type: git:release
          options:
            description: ${LATEST_CHANGE_LOG}
